
package: assiopay
author: Kreatif GmbH
version: '0.0.1'

page:
    title: translate:assiopay
    perm: assiopay
    subpages:
        settings:
            title: translate:assiopay
            hidden: true
